# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # image
  config.vm.box = "ubuntu/bionic64"

  # mount
  config.vm.synced_folder "../../", "/vagrant_data"
  
  # for Jupyter Notebook
  config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.33"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end
end
